version: '3.7'
volumes:
  postgres:
  bundle_cache:
  node_modules:
  redis:
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    command: sh -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    #BB Changed to allow for newer version of activesupport
    #command: sh -c "bundle _2.0.0.pre.3_ install && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - bundle_cache:/bundle:cached
      - node_modules:/app/node_modules:cached
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      #WEBPACKER_DEV_SERVER_HOST: webpacker
      DISABLE_SPRING: 1
