version: '3.7'

services:
  meek-db:
    image: postgres:9.6.12
    restart: "no"
    environment:
      POSTGRES_DB: meek_development_pg
      POSTGRES_USER: pe
      POSTGRES_PASSWORD: pe
    ports:
      - 5432:5432
#    volumes:
#      - meek-postgres:/var/lib/postgresql/data # Store Postgres data ./pgdata

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8085:8080

# fix for windows: https://github.com/docker-library/postgres/issues/435#issuecomment-387598016
#volumes:
#  meek-postgres: