# NOTE: These data was copied from migration files before migrations were squashed.

StaticPage.create(name: 'About', title: 'About', content: 'Coming Soon', subject: 0)
StaticPage.create(name: 'Terms Of Use', title: 'Terms Of Use', content: 'Coming Soon', subject: 1)
StaticPage.create(name: 'Privacy Policy', title: 'Privacy Policy', content: 'Coming Soon', subject: 2)


Country.create(iso2_code: 'AF', iso3_code: 'AFG', name: 'Afghanistan')
Country.create(iso2_code: 'AX', iso3_code: 'ALA', name: 'Åland Islands')
Country.create(iso2_code: 'AL', iso3_code: 'ALB', name: 'Albania')
Country.create(iso2_code: 'DZ', iso3_code: 'DZA', name: 'Algeria')
Country.create(iso2_code: 'AS', iso3_code: 'ASM', name: 'American Samoa')
Country.create(iso2_code: 'AD', iso3_code: 'AND', name: 'Andorra')
Country.create(iso2_code: 'AO', iso3_code: 'AGO', name: 'Angola')
Country.create(iso2_code: 'AI', iso3_code: 'AIA', name: 'Anguilla')
Country.create(iso2_code: 'AQ', iso3_code: 'ATA', name: 'Antarctica')
Country.create(iso2_code: 'AG', iso3_code: 'ATG', name: 'Antigua and Barbuda')
Country.create(iso2_code: 'AR', iso3_code: 'ARG', name: 'Argentina')
Country.create(iso2_code: 'AM', iso3_code: 'ARM', name: 'Armenia')
Country.create(iso2_code: 'AW', iso3_code: 'ABW', name: 'Aruba')
Country.create(iso2_code: 'AU', iso3_code: 'AUS', name: 'Australia')
Country.create(iso2_code: 'AT', iso3_code: 'AUT', name: 'Austria')
Country.create(iso2_code: 'AZ', iso3_code: 'AZE', name: 'Azerbaijan')
Country.create(iso2_code: 'BS', iso3_code: 'BHS', name: 'Bahamas')
Country.create(iso2_code: 'BH', iso3_code: 'BHR', name: 'Bahrain')
Country.create(iso2_code: 'BD', iso3_code: 'BGD', name: 'Bangladesh')
Country.create(iso2_code: 'BB', iso3_code: 'BRB', name: 'Barbados')
Country.create(iso2_code: 'BY', iso3_code: 'BLR', name: 'Belarus')
Country.create(iso2_code: 'BE', iso3_code: 'BEL', name: 'Belgium')
Country.create(iso2_code: 'BZ', iso3_code: 'BLZ', name: 'Belize')
Country.create(iso2_code: 'BJ', iso3_code: 'BEN', name: 'Benin')
Country.create(iso2_code: 'BM', iso3_code: 'BMU', name: 'Bermuda')
Country.create(iso2_code: 'BT', iso3_code: 'BTN', name: 'Bhutan')
Country.create(iso2_code: 'BO', iso3_code: 'BOL', name: 'Bolivia')
Country.create(iso2_code: 'BA', iso3_code: 'BIH', name: 'Bosnia and Herzegovina')
Country.create(iso2_code: 'BW', iso3_code: 'BWA', name: 'Botswana')
Country.create(iso2_code: 'BV', iso3_code: 'BVT', name: 'Bouvet Island')
Country.create(iso2_code: 'BR', iso3_code: 'BRA', name: 'Brazil')
Country.create(iso2_code: 'IO', iso3_code: 'IOT', name: 'British Indian Ocean Territory')
Country.create(iso2_code: 'VG', iso3_code: 'VGB', name: 'British Virgin Islands')
Country.create(iso2_code: 'BN', iso3_code: 'BRN', name: 'Brunei')
Country.create(iso2_code: 'BG', iso3_code: 'BGR', name: 'Bulgaria')
Country.create(iso2_code: 'BF', iso3_code: 'BFA', name: 'Burkina Faso')
Country.create(iso2_code: 'BI', iso3_code: 'BDI', name: 'Burundi')
Country.create(iso2_code: 'KH', iso3_code: 'KHM', name: 'Cambodia')
Country.create(iso2_code: 'CM', iso3_code: 'CMR', name: 'Cameroon')
Country.create(iso2_code: 'CA', iso3_code: 'CAN', name: 'Canada')
Country.create(iso2_code: 'CV', iso3_code: 'CPV', name: 'Cape Verde')
Country.create(iso2_code: 'KY', iso3_code: 'CYM', name: 'Cayman Islands')
Country.create(iso2_code: 'CF', iso3_code: 'CAF', name: 'Central African Republic')
Country.create(iso2_code: 'TD', iso3_code: 'TCD', name: 'Chad')
Country.create(iso2_code: 'CL', iso3_code: 'CHL', name: 'Chile')
Country.create(iso2_code: 'CN', iso3_code: 'CHN', name: 'China')
Country.create(iso2_code: 'CX', iso3_code: 'CXR', name: 'Christmas Island')
Country.create(iso2_code: 'CC', iso3_code: 'CCK', name: 'Cocos [Keeling] Islands')
Country.create(iso2_code: 'CO', iso3_code: 'COL', name: 'Colombia')
Country.create(iso2_code: 'KM', iso3_code: 'COM', name: 'Comoros')
Country.create(iso2_code: 'CG', iso3_code: 'COG', name: 'Congo - Brazzaville')
Country.create(iso2_code: 'CD', iso3_code: 'COD', name: 'Congo - Kinshasa')
Country.create(iso2_code: 'CK', iso3_code: 'COK', name: 'Cook Islands')
Country.create(iso2_code: 'CR', iso3_code: 'CRI', name: 'Costa Rica')
Country.create(iso2_code: 'CI', iso3_code: 'CIV', name: 'Côte d’Ivoire')
Country.create(iso2_code: 'HR', iso3_code: 'HRV', name: 'Croatia')
Country.create(iso2_code: 'CU', iso3_code: 'CUB', name: 'Cuba')
Country.create(iso2_code: 'CY', iso3_code: 'CYP', name: 'Cyprus')
Country.create(iso2_code: 'CZ', iso3_code: 'CZE', name: 'Czech Republic')
Country.create(iso2_code: 'DK', iso3_code: 'DNK', name: 'Denmark')
Country.create(iso2_code: 'DJ', iso3_code: 'DJI', name: 'Djibouti')
Country.create(iso2_code: 'DM', iso3_code: 'DMA', name: 'Dominica')
Country.create(iso2_code: 'DO', iso3_code: 'DOM', name: 'Dominican Republic')
Country.create(iso2_code: 'EC', iso3_code: 'ECU', name: 'Ecuador')
Country.create(iso2_code: 'EG', iso3_code: 'EGY', name: 'Egypt')
Country.create(iso2_code: 'SV', iso3_code: 'SLV', name: 'El Salvador')
Country.create(iso2_code: 'GQ', iso3_code: 'GNQ', name: 'Equatorial Guinea')
Country.create(iso2_code: 'ER', iso3_code: 'ERI', name: 'Eritrea')
Country.create(iso2_code: 'EE', iso3_code: 'EST', name: 'Estonia')
Country.create(iso2_code: 'ET', iso3_code: 'ETH', name: 'Ethiopia')
Country.create(iso2_code: 'FK', iso3_code: 'FLK', name: 'Falkland Islands')
Country.create(iso2_code: 'FO', iso3_code: 'FRO', name: 'Faroe Islands')
Country.create(iso2_code: 'FJ', iso3_code: 'FJI', name: 'Fiji')
Country.create(iso2_code: 'FI', iso3_code: 'FIN', name: 'Finland')
Country.create(iso2_code: 'FR', iso3_code: 'FRA', name: 'France')
Country.create(iso2_code: 'GF', iso3_code: 'GUF', name: 'French Guiana')
Country.create(iso2_code: 'PF', iso3_code: 'PYF', name: 'French Polynesia')
Country.create(iso2_code: 'TF', iso3_code: 'ATF', name: 'French Southern Territories')
Country.create(iso2_code: 'GA', iso3_code: 'GAB', name: 'Gabon')
Country.create(iso2_code: 'GM', iso3_code: 'GMB', name: 'Gambia')
Country.create(iso2_code: 'GE', iso3_code: 'GEO', name: 'Georgia')
Country.create(iso2_code: 'DE', iso3_code: 'DEU', name: 'Germany')
Country.create(iso2_code: 'GH', iso3_code: 'GHA', name: 'Ghana')
Country.create(iso2_code: 'GI', iso3_code: 'GIB', name: 'Gibraltar')
Country.create(iso2_code: 'GR', iso3_code: 'GRC', name: 'Greece')
Country.create(iso2_code: 'GL', iso3_code: 'GRL', name: 'Greenland')
Country.create(iso2_code: 'GD', iso3_code: 'GRD', name: 'Grenada')
Country.create(iso2_code: 'GP', iso3_code: 'GLP', name: 'Guadeloupe')
Country.create(iso2_code: 'GU', iso3_code: 'GUM', name: 'Guam')
Country.create(iso2_code: 'GT', iso3_code: 'GTM', name: 'Guatemala')
Country.create(iso2_code: 'GG', iso3_code: 'GGY', name: 'Guernsey')
Country.create(iso2_code: 'GN', iso3_code: 'GIN', name: 'Guinea')
Country.create(iso2_code: 'GW', iso3_code: 'GNB', name: 'Guinea-Bissau')
Country.create(iso2_code: 'GY', iso3_code: 'GUY', name: 'Guyana')
Country.create(iso2_code: 'HT', iso3_code: 'HTI', name: 'Haiti')
Country.create(iso2_code: 'HM', iso3_code: 'HMD', name: 'Heard Island and McDonald Islands')
Country.create(iso2_code: 'HN', iso3_code: 'HND', name: 'Honduras')
Country.create(iso2_code: 'HK', iso3_code: 'HKG', name: 'Hong Kong SAR China')
Country.create(iso2_code: 'HU', iso3_code: 'HUN', name: 'Hungary')
Country.create(iso2_code: 'IS', iso3_code: 'ISL', name: 'Iceland')
Country.create(iso2_code: 'IN', iso3_code: 'IND', name: 'India')
Country.create(iso2_code: 'ID', iso3_code: 'IDN', name: 'Indonesia')
Country.create(iso2_code: 'IR', iso3_code: 'IRN', name: 'Iran')
Country.create(iso2_code: 'IQ', iso3_code: 'IRQ', name: 'Iraq')
Country.create(iso2_code: 'IE', iso3_code: 'IRL', name: 'Ireland')
Country.create(iso2_code: 'IM', iso3_code: 'IMN', name: 'Isle of Man')
Country.create(iso2_code: 'IL', iso3_code: 'ISR', name: 'Israel')
Country.create(iso2_code: 'IT', iso3_code: 'ITA', name: 'Italy')
Country.create(iso2_code: 'JM', iso3_code: 'JAM', name: 'Jamaica')
Country.create(iso2_code: 'JP', iso3_code: 'JPN', name: 'Japan')
Country.create(iso2_code: 'JE', iso3_code: 'JEY', name: 'Jersey')
Country.create(iso2_code: 'JO', iso3_code: 'JOR', name: 'Jordan')
Country.create(iso2_code: 'KZ', iso3_code: 'KAZ', name: 'Kazakhstan')
Country.create(iso2_code: 'KE', iso3_code: 'KEN', name: 'Kenya')
Country.create(iso2_code: 'KI', iso3_code: 'KIR', name: 'Kiribati')
Country.create(iso2_code: 'KW', iso3_code: 'KWT', name: 'Kuwait')
Country.create(iso2_code: 'KG', iso3_code: 'KGZ', name: 'Kyrgyzstan')
Country.create(iso2_code: 'LA', iso3_code: 'LAO', name: 'Laos')
Country.create(iso2_code: 'LV', iso3_code: 'LVA', name: 'Latvia')
Country.create(iso2_code: 'LB', iso3_code: 'LBN', name: 'Lebanon')
Country.create(iso2_code: 'LS', iso3_code: 'LSO', name: 'Lesotho')
Country.create(iso2_code: 'LR', iso3_code: 'LBR', name: 'Liberia')
Country.create(iso2_code: 'LY', iso3_code: 'LBY', name: 'Libya')
Country.create(iso2_code: 'LI', iso3_code: 'LIE', name: 'Liechtenstein')
Country.create(iso2_code: 'LT', iso3_code: 'LTU', name: 'Lithuania')
Country.create(iso2_code: 'LU', iso3_code: 'LUX', name: 'Luxembourg')
Country.create(iso2_code: 'MO', iso3_code: 'MAC', name: 'Macau SAR China')
Country.create(iso2_code: 'MK', iso3_code: 'MKD', name: 'Macedonia')
Country.create(iso2_code: 'MG', iso3_code: 'MDG', name: 'Madagascar')
Country.create(iso2_code: 'MW', iso3_code: 'MWI', name: 'Malawi')
Country.create(iso2_code: 'MY', iso3_code: 'MYS', name: 'Malaysia')
Country.create(iso2_code: 'MV', iso3_code: 'MDV', name: 'Maldives')
Country.create(iso2_code: 'ML', iso3_code: 'MLI', name: 'Mali')
Country.create(iso2_code: 'MT', iso3_code: 'MLT', name: 'Malta')
Country.create(iso2_code: 'MH', iso3_code: 'MHL', name: 'Marshall Islands')
Country.create(iso2_code: 'MQ', iso3_code: 'MTQ', name: 'Martinique')
Country.create(iso2_code: 'MR', iso3_code: 'MRT', name: 'Mauritania')
Country.create(iso2_code: 'MU', iso3_code: 'MUS', name: 'Mauritius')
Country.create(iso2_code: 'YT', iso3_code: 'MYT', name: 'Mayotte')
Country.create(iso2_code: 'MX', iso3_code: 'MEX', name: 'Mexico')
Country.create(iso2_code: 'FM', iso3_code: 'FSM', name: 'Micronesia')
Country.create(iso2_code: 'MD', iso3_code: 'MDA', name: 'Moldova')
Country.create(iso2_code: 'MC', iso3_code: 'MCO', name: 'Monaco')
Country.create(iso2_code: 'MN', iso3_code: 'MNG', name: 'Mongolia')
Country.create(iso2_code: 'ME', iso3_code: 'MNE', name: 'Montenegro')
Country.create(iso2_code: 'MS', iso3_code: 'MSR', name: 'Montserrat')
Country.create(iso2_code: 'MA', iso3_code: 'MAR', name: 'Morocco')
Country.create(iso2_code: 'MZ', iso3_code: 'MOZ', name: 'Mozambique')
Country.create(iso2_code: 'MM', iso3_code: 'MMR', name: 'Myanmar [Burma]')
Country.create(iso2_code: 'NA', iso3_code: 'NAM', name: 'Namibia')
Country.create(iso2_code: 'NR', iso3_code: 'NRU', name: 'Nauru')
Country.create(iso2_code: 'NP', iso3_code: 'NPL', name: 'Nepal')
Country.create(iso2_code: 'NL', iso3_code: 'NLD', name: 'Netherlands')
Country.create(iso2_code: 'AN', iso3_code: 'ANT', name: 'Netherlands Antilles')
Country.create(iso2_code: 'NC', iso3_code: 'NCL', name: 'New Caledonia')
Country.create(iso2_code: 'NZ', iso3_code: 'NZL', name: 'New Zealand')
Country.create(iso2_code: 'NI', iso3_code: 'NIC', name: 'Nicaragua')
Country.create(iso2_code: 'NE', iso3_code: 'NER', name: 'Niger')
Country.create(iso2_code: 'NG', iso3_code: 'NGA', name: 'Nigeria')
Country.create(iso2_code: 'NU', iso3_code: 'NIU', name: 'Niue')
Country.create(iso2_code: 'NF', iso3_code: 'NFK', name: 'Norfolk Island')
Country.create(iso2_code: 'KP', iso3_code: 'PRK', name: 'North Korea')
Country.create(iso2_code: 'MP', iso3_code: 'MNP', name: 'Northern Mariana Islands')
Country.create(iso2_code: 'NO', iso3_code: 'NOR', name: 'Norway')
Country.create(iso2_code: 'OM', iso3_code: 'OMN', name: 'Oman')
Country.create(iso2_code: 'PK', iso3_code: 'PAK', name: 'Pakistan')
Country.create(iso2_code: 'PW', iso3_code: 'PLW', name: 'Palau')
Country.create(iso2_code: 'PS', iso3_code: 'PSE', name: 'Palestinian Territories')
Country.create(iso2_code: 'PA', iso3_code: 'PAN', name: 'Panama')
Country.create(iso2_code: 'PG', iso3_code: 'PNG', name: 'Papua New Guinea')
Country.create(iso2_code: 'PY', iso3_code: 'PRY', name: 'Paraguay')
Country.create(iso2_code: 'PE', iso3_code: 'PER', name: 'Peru')
Country.create(iso2_code: 'PH', iso3_code: 'PHL', name: 'Philippines')
Country.create(iso2_code: 'PN', iso3_code: 'PCN', name: 'Pitcairn Islands')
Country.create(iso2_code: 'PL', iso3_code: 'POL', name: 'Poland')
Country.create(iso2_code: 'PT', iso3_code: 'PRT', name: 'Portugal')
Country.create(iso2_code: 'PR', iso3_code: 'PRI', name: 'Puerto Rico')
Country.create(iso2_code: 'QA', iso3_code: 'QAT', name: 'Qatar')
Country.create(iso2_code: 'RE', iso3_code: 'REU', name: 'Réunion')
Country.create(iso2_code: 'RO', iso3_code: 'ROU', name: 'Romania')
Country.create(iso2_code: 'RU', iso3_code: 'RUS', name: 'Russia')
Country.create(iso2_code: 'RW', iso3_code: 'RWA', name: 'Rwanda')
Country.create(iso2_code: 'BL', iso3_code: 'BLM', name: 'Saint Barthélemy')
Country.create(iso2_code: 'SH', iso3_code: 'SHN', name: 'Saint Helena')
Country.create(iso2_code: 'KN', iso3_code: 'KNA', name: 'Saint Kitts and Nevis')
Country.create(iso2_code: 'LC', iso3_code: 'LCA', name: 'Saint Lucia')
Country.create(iso2_code: 'MF', iso3_code: 'MAF', name: 'Saint Martin')
Country.create(iso2_code: 'PM', iso3_code: 'SPM', name: 'Saint Pierre and Miquelon')
Country.create(iso2_code: 'VC', iso3_code: 'VCT', name: 'Saint Vincent and the Grenadines')
Country.create(iso2_code: 'WS', iso3_code: 'WSM', name: 'Samoa')
Country.create(iso2_code: 'SM', iso3_code: 'SMR', name: 'San Marino')
Country.create(iso2_code: 'ST', iso3_code: 'STP', name: 'São Tomé and Príncipe')
Country.create(iso2_code: 'SA', iso3_code: 'SAU', name: 'Saudi Arabia')
Country.create(iso2_code: 'SN', iso3_code: 'SEN', name: 'Senegal')
Country.create(iso2_code: 'RS', iso3_code: 'SRB', name: 'Serbia')
Country.create(iso2_code: 'SC', iso3_code: 'SYC', name: 'Seychelles')
Country.create(iso2_code: 'SL', iso3_code: 'SLE', name: 'Sierra Leone')
Country.create(iso2_code: 'SG', iso3_code: 'SGP', name: 'Singapore')
Country.create(iso2_code: 'SK', iso3_code: 'SVK', name: 'Slovakia')
Country.create(iso2_code: 'SI', iso3_code: 'SVN', name: 'Slovenia')
Country.create(iso2_code: 'SB', iso3_code: 'SLB', name: 'Solomon Islands')
Country.create(iso2_code: 'SO', iso3_code: 'SOM', name: 'Somalia')
Country.create(iso2_code: 'ZA', iso3_code: 'ZAF', name: 'South Africa')
Country.create(iso2_code: 'GS', iso3_code: 'SGS', name: 'South Georgia and the South Sandwich Islands')
Country.create(iso2_code: 'KR', iso3_code: 'KOR', name: 'South Korea')
Country.create(iso2_code: 'ES', iso3_code: 'ESP', name: 'Spain')
Country.create(iso2_code: 'LK', iso3_code: 'LKA', name: 'Sri Lanka')
Country.create(iso2_code: 'SD', iso3_code: 'SDN', name: 'Sudan')
Country.create(iso2_code: 'SR', iso3_code: 'SUR', name: 'Suriname')
Country.create(iso2_code: 'SJ', iso3_code: 'SJM', name: 'Svalbard and Jan Mayen')
Country.create(iso2_code: 'SZ', iso3_code: 'SWZ', name: 'Swaziland')
Country.create(iso2_code: 'SE', iso3_code: 'SWE', name: 'Sweden')
Country.create(iso2_code: 'CH', iso3_code: 'CHE', name: 'Switzerland')
Country.create(iso2_code: 'SY', iso3_code: 'SYR', name: 'Syria')
Country.create(iso2_code: 'TW', iso3_code: 'TWN', name: 'Taiwan')
Country.create(iso2_code: 'TJ', iso3_code: 'TJK', name: 'Tajikistan')
Country.create(iso2_code: 'TZ', iso3_code: 'TZA', name: 'Tanzania')
Country.create(iso2_code: 'TH', iso3_code: 'THA', name: 'Thailand')
Country.create(iso2_code: 'TL', iso3_code: 'TLS', name: 'Timor-Leste')
Country.create(iso2_code: 'TG', iso3_code: 'TGO', name: 'Togo')
Country.create(iso2_code: 'TK', iso3_code: 'TKL', name: 'Tokelau')
Country.create(iso2_code: 'TO', iso3_code: 'TON', name: 'Tonga')
Country.create(iso2_code: 'TT', iso3_code: 'TTO', name: 'Trinidad and Tobago')
Country.create(iso2_code: 'TN', iso3_code: 'TUN', name: 'Tunisia')
Country.create(iso2_code: 'TR', iso3_code: 'TUR', name: 'Turkey')
Country.create(iso2_code: 'TM', iso3_code: 'TKM', name: 'Turkmenistan')
Country.create(iso2_code: 'TC', iso3_code: 'TCA', name: 'Turks and Caicos Islands')
Country.create(iso2_code: 'TV', iso3_code: 'TUV', name: 'Tuvalu')
Country.create(iso2_code: 'UM', iso3_code: 'UMI', name: 'U.S. Minor Outlying Islands')
Country.create(iso2_code: 'VI', iso3_code: 'VIR', name: 'U.S. Virgin Islands')
Country.create(iso2_code: 'UG', iso3_code: 'UGA', name: 'Uganda')
Country.create(iso2_code: 'UA', iso3_code: 'UKR', name: 'Ukraine')
Country.create(iso2_code: 'AE', iso3_code: 'ARE', name: 'United Arab Emirates')
Country.create(iso2_code: 'GB', iso3_code: 'GBR', name: 'United Kingdom')
Country.create(iso2_code: 'US', iso3_code: 'USA', name: 'United States')
Country.create(iso2_code: 'UY', iso3_code: 'URY', name: 'Uruguay')
Country.create(iso2_code: 'UZ', iso3_code: 'UZB', name: 'Uzbekistan')
Country.create(iso2_code: 'VU', iso3_code: 'VUT', name: 'Vanuatu')
Country.create(iso2_code: 'VA', iso3_code: 'VAT', name: 'Vatican City')
Country.create(iso2_code: 'VE', iso3_code: 'VEN', name: 'Venezuela')
Country.create(iso2_code: 'VN', iso3_code: 'VNM', name: 'Vietnam')
Country.create(iso2_code: 'WF', iso3_code: 'WLF', name: 'Wallis and Futuna')
Country.create(iso2_code: 'EH', iso3_code: 'ESH', name: 'Western Sahara')
Country.create(iso2_code: 'YE', iso3_code: 'YEM', name: 'Yemen')
Country.create(iso2_code: 'ZM', iso3_code: 'ZMB', name: 'Zambia')
Country.create(iso2_code: 'ZW', iso3_code: 'ZWE', name: 'Zimbabwe')


Region.create(code: 'LT-UT', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'BL', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'LT-VL', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'KN', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Ādažu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NO', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Aglonas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'OO', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'LV-AI', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SB', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Aizputes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'ST', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Aknīstes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'TI', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Alojas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'VB', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'Alsungas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'WI', name: '', country: Country.find_by(iso2_code: 'AT'))
Region.create(code: 'LV-AL', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'AB', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Amatas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BC', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Apes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'MB', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Auces novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NB', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Babītes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NL', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Baldones novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NT', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Baltinavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NS', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'LV-BL', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NU', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'LV-BU', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'ON', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Beverīnas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'PE', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Brocēnu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'QC', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Burtnieku novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SK', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'Carnikavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'YT', name: '', country: Country.find_by(iso2_code: 'CA'))
Region.create(code: 'LV-CE', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'AG', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Cesvaines novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'AR', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Ciblas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'AI', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Dagdas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BL', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-DGV', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BS', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-DA', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BE', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-DO', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'FR', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Dundagas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'GE', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Durbes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'GL', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Engures novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'GR', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Ērgļu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'JU', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Garkalnes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'LU', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Grobiņas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NE', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-GU', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NW', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Iecavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'OW', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Ikšķiles novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SH', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Ilūkstes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SZ', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Inčukalna novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SO', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Jaunjelgavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SG', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Jaunpiebalgas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'TI', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Jaunpils novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'TG', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Jēkabpils', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'UR', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-JK', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'VD', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-JEL', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'VS', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-JL', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'ZG', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'LV-JUR', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'ZH', name: '', country: Country.find_by(iso2_code: 'CH'))
Region.create(code: 'Kandavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BAW', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Kārsavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BAY', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Ķeguma novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BER', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Ķekavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BRG', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Kokneses novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'BRE', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-KR', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'HAM', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Krimuldas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'HES', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Krustpils novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'MEC', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-KU', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NDS', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Lielvārdes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'NRW', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-LPX', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'RHE', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-LE', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SAR', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Līgatnes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SAS', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-LM', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SAC', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Līvānu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'SCN', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'Lubānas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'THE', name: '', country: Country.find_by(iso2_code: 'DE'))
Region.create(code: 'LV-LU', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-37', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'LV-MA', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-39', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Mālpils novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-44', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Mārupes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-51', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Mazsalacas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-49', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Naukšēnu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-59', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Neretas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-57', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Nīcas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-67', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'LV-OG', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-65', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Olaines novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-70', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Ozolnieku novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-74', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Pārgaujas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-78', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Pāvilostas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-82', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Pļaviņu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-84', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'LV-PR', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'EE-86', name: '', country: Country.find_by(iso2_code: 'EE'))
Region.create(code: 'Priekules novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'A Coruсa', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Priekuļu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Alava', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Raunas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Albacete', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-REZ', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Alicante', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-RE', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Almeria', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Riebiņu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Asturias', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-RIX', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Avila', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-RI', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Badajoz', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Rojas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Baleares', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Ropažu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Barcelona', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Rucavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Burgos', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Rugāju novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Caceres', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Rūjienas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Cadiz', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Rundāles novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Cantabria', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Salacgrīvas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Castellon', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Salas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Ceuta', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Salaspils novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Ciudad Real', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-SA', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Cordoba', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Saulkrastu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Cuenca', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Sējas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Girona', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Siguldas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Granada', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Skrīveru novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Guadalajara', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Skrundas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Guipuzcoa', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Smiltenes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Huelva', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Stopiņu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Huesca', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Strenču novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Jaen', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-TA', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'La Rioja', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Tērvetes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Las Palmas', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-TU', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Leon', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Vaiņodes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Lleida', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-VK', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Lugo', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Valmiera', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Madrid', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-VM', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Malaga', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Varakļānu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Melilla', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Vārkavas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Murcia', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Vecpiebalgas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Navarra', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Vecumnieku novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Ourense', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-VEN', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Palencia', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'LV-VE', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Pontevedra', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Viesītes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Salamanca', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Viļakas novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Santa Cruz de Tenerife', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Viļānu novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Segovia', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'Zilupes novads', name: '', country: Country.find_by(iso2_code: 'LV'))
Region.create(code: 'Sevilla', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'AB', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Soria', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'AR', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Tarragona', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'AG', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Teruel', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BC', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Toledo', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BH', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Valencia', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BN', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Valladolid', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BT', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Vizcaya', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BR', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Zamora', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'BV', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Zaragoza', name: '', country: Country.find_by(iso2_code: 'ES'))
Region.create(code: 'B', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Ahvenanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'BZ', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Etelä-Karjala', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'CL', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Etelä-Pohjanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'CS', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Etelä-Savo', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'CJ', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Itä-Uusimaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'CT', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Kainuu', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'CV', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Kanta-Häme', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'DB', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Keski-Pohjanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'DJ', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Keski-Suomi', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'GL', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Kymenlaakso', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'GR', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Lappi', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'GJ', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Päijät-Häme', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'HR', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Pirkanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'HD', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Pohjanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'IL', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Pohjois-Karjala', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'IS', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Pohjois-Pohjanmaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'IF', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Pohjois-Savo', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'MM', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Satakunta', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'MH', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Uusimaa', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'MS', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: 'Varsinais-Suomi', name: '', country: Country.find_by(iso2_code: 'FI'))
Region.create(code: 'NT', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '1', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'OT', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '2', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'PH', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '3', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'SJ', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '4', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'SM', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '6', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'SB', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '7', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'SV', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '8', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'TR', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '9', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'TM', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '10', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'TL', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '11', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'VL', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '12', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'VS', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '67', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'VN', name: '', country: Country.find_by(iso2_code: 'RO'))
Region.create(code: '13', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '14', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '15', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '16', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '17', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '18', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '19', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '2A', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '21', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '22', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '23', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '79', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '24', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '25', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '26', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '91', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '27', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '28', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '29', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '30', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '32', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '33', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '68', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '2B', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '31', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '43', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '52', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '70', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '74', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '87', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '5', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '65', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '92', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '34', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '35', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '36', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '37', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '38', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '39', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '40', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '41', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '42', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '44', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '45', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '46', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '47', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '48', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '49', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '50', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '51', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '53', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '54', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '55', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '56', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '57', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '58', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '59', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '60', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '61', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '75', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '62', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '63', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '64', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '66', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '69', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '71', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '72', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '73', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '77', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '76', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '93', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '80', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '81', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '82', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '90', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '95', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '94', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '83', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '84', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '85', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '86', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '88', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '89', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: '78', name: '', country: Country.find_by(iso2_code: 'FR'))
Region.create(code: 'LT-AL', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-KU', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-KL', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-MR', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-PN', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-SA', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-TA', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'LT-TE', name: '', country: Country.find_by(iso2_code: 'LT'))
Region.create(code: 'AL', name: 'Alabama', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AK', name: 'Alaska', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AS', name: 'American Samoa', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AZ', name: 'Arizona', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AR', name: 'Arkansas', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AF', name: 'Armed Forces Africa', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AA', name: 'Armed Forces Americas', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AC', name: 'Armed Forces Canada', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AE', name: 'Armed Forces Europe', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AM', name: 'Armed Forces Middle East', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'AP', name: 'Armed Forces Pacific', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'CA', name: 'California', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'CO', name: 'Colorado', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'CT', name: 'Connecticut', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'DE', name: 'Delaware', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'DC', name: 'District of Columbia', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'FM', name: 'Federated States Of Micronesia', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'FL', name: 'Florida', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'GA', name: 'Georgia', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'GU', name: 'Guam', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'HI', name: 'Hawaii', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'ID', name: 'Idaho', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'IL', name: 'Illinois', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'IN', name: 'Indiana', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'IA', name: 'Iowa', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'KS', name: 'Kansas', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'KY', name: 'Kentucky', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'LA', name: 'Louisiana', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'ME', name: 'Maine', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MH', name: 'Marshall Islands', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MD', name: 'Maryland', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MA', name: 'Massachusetts', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MI', name: 'Michigan', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MN', name: 'Minnesota', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MS', name: 'Mississippi', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MO', name: 'Missouri', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MT', name: 'Montana', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NE', name: 'Nebraska', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NV', name: 'Nevada', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NH', name: 'New Hampshire', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NJ', name: 'New Jersey', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NM', name: 'New Mexico', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NY', name: 'New York', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'NC', name: 'North Carolina', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'ND', name: 'North Dakota', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'MP', name: 'Northern Mariana Islands', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'OH', name: 'Ohio', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'OK', name: 'Oklahoma', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'OR', name: 'Oregon', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'PW', name: 'Palau', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'PA', name: 'Pennsylvania', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'PR', name: 'Puerto Rico', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'RI', name: 'Rhode Island', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'SC', name: 'South Carolina', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'SD', name: 'South Dakota', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'TN', name: 'Tennessee', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'TX', name: 'Texas', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'UT', name: 'Utah', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'VT', name: 'Vermont', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'VI', name: 'Virgin Islands', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'VA', name: 'Virginia', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'WA', name: 'Washington', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'WV', name: 'West Virginia', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'WI', name: 'Wisconsin', country: Country.find_by(iso2_code: 'US'))
Region.create(code: 'WY', name: 'Wyoming', country: Country.find_by(iso2_code: 'US'))
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?